[build]
builder = "DOCKERFILE"
dockerfilePath = "identity-service/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
