[build]
builder = "nixpacks"
buildCommand = "cd identity-service && ./mvnw package -DskipTests"
watchPatterns = ["identity-service/**"]

[deploy]
startCommand = "cd identity-service && java -jar target/*.jar"
restartPolicyType = "ON_FAILURE"

[variables]
NIXPACKS_JAVA_VERSION = "17"
