name: Deploy Identity Service to Railway

on:
  push:
    branches:
      - main  # Trigger when commits are pushed to the main branch
    paths:
      - 'identity-service/**'  # Only trigger when changes are in the identity-service directory
      - 'railway.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      # Step 4: Login to Railway
      - name: Login to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      # Step 5: Deploy to Railway
      - name: Deploy Identity Service to Railway
        working-directory: identity-service
        run: |
          railway up --service identity-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Step 6: Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Identity Service deployed to Railway successfully!"