name: Deploy Identity Service to Railway

on:
  push:
    branches:
      - main
    paths:
      - "identity-service/**"
      - ".github/workflows/deploy-identity-service.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./identity-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: ./mvnw package -DskipTests

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: echo "${{ secrets.RAILWAY_TOKEN }}" | railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: |
          # Deploy to the specific service
          railway up --service identity-service --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
