name: Deploy Identity Service to Railway

on:
  push:
    branches:
      - main
    paths:
      - "identity-service/**"
      - ".github/workflows/deploy-identity-service.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug step to check files
      - name: List files in identity-service
        run: ls -la identity-service/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        working-directory: ./identity-service
        run: ./mvnw package -DskipTests

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp identity-service/target/*.jar deployment/app.jar
          cat <<EOF > deployment/Dockerfile
          FROM eclipse-temurin:17-jre-alpine
          WORKDIR /app
          COPY app.jar app.jar
          ENTRYPOINT ["java", "-jar", "app.jar"]
          EOF
          ls -la deployment/
          echo "Deployment package created successfully."

      # Install and use railway-deploy GitHub Action
      - name: Deploy to Railway
        uses: devtomio/action-railway@v1.2.0
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: identity-service
          directory: ./deployment
          detach: true
