name: Deploy Identity Service to Railway

on:
  push:
    branches: [main]
    paths:
      - 'identity-service/**'
      - 'railway.toml'
      - '.github/workflows/deploy-identity-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Simplified approach using curl to trigger Railway deployment
      - name: Trigger Railway Deployment
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            "https://backboard.railway.app/api/projects/${{ secrets.RAILWAY_PROJECT_ID }}/deploy" \
            -d '{}'
