name: Deploy Identity Service to Railway

on:
  push:
    branches: [main]
    paths:
      - 'identity-service/**'
      - 'railway.toml'
      - '.github/workflows/deploy-identity-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -f identity-service/pom.xml --file identity-service/pom.xml -DskipTests

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: |
          cd identity-service
          # First create a new service if it doesn't exist
          railway service create identity-service || echo "Service might already exist"
          # Link to the service
          railway link --service identity-service
          # Deploy to the linked service
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
