name: Deploy Identity Service to Railway

on:
  push:
    branches: [main]
    paths:
      - 'identity-service/**'
      - 'railway.toml'
      - '.github/workflows/deploy-identity-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -f identity-service/pom.xml --file identity-service/pom.xml -DskipTests

      - name: Deploy to Railway
        uses: railway/cli-action@v2
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          workdir: identity-service
