name: Deploy Identity Service to Railway

on:
  push:
    branches:
      - main
    paths:
      - "identity-service/**"
      - ".github/workflows/deploy-identity-service.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug step to check files
      - name: List files in identity-service
        run: |
          ls -la identity-service/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        working-directory: ./identity-service
        run: ./mvnw package -DskipTests

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp identity-service/target/*.jar deployment/
          cp identity-service/Dockerfile deployment/
          echo "FROM eclipse-temurin:17-jre-alpine" > deployment/Dockerfile
          echo "WORKDIR /app" >> deployment/Dockerfile
          echo "COPY *.jar app.jar" >> deployment/Dockerfile
          echo "ENTRYPOINT [\"java\", \"-jar\", \"app.jar\"]" >> deployment/Dockerfile
          ls -la deployment/

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: echo "${{ secrets.RAILWAY_TOKEN }}" | railway login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        working-directory: ./deployment
        run: |
          railway up --service identity-service --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
