name: Deploy Identity Service to Railway

on:
  push:
    branches: [main]
    paths:
      - 'identity-service/**'
      - 'railway.toml'
      - '.github/workflows/deploy-identity-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
        
      - name: Login to Railway
        run: |
          echo "${{ secrets.RAILWAY_TOKEN }}" | railway login --browserless
        
      - name: Deploy to Railway
        run: |
          cd identity-service
          railway link --environment production
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
