name: Deploy Identity Service to Railway

on:
  push:
    branches: [main]
    paths:
      - 'identity-service/**'
      - 'railway.toml'
      - '.github/workflows/deploy-identity-service.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Railway CLI version
        run: railway --version
        
      - name: Deploy identity-service to Railway
        run: |
          # Change to identity-service directory first
          cd identity-service
          # Deploy using current directory
          railway init --name="identity-service"
          railway up
