name: Deploy Identity Service JAR to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'identity-service/**'
      - '.github/workflows/deploy-identity-service.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd identity-service
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Create deployment directory
        run: |
          mkdir -p railway-deploy
          cp identity-service/target/*.jar railway-deploy/app.jar
          echo "web: java -Dserver.port=\$PORT -jar app.jar" > railway-deploy/Procfile

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        working-directory: railway-deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --environment production --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up
