name: Deploy Identity Service to Railway

on:
  push:
    branches:
      - main
    paths:
      - "identity-service/**"
      - ".github/workflows/deploy-identity-service.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in identity-service
        run: ls -la identity-service/

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        working-directory: ./identity-service
        run: ./mvnw package -DskipTests

      - name: Create simple deployment
        run: |
          mkdir -p deployment
          cp identity-service/target/*.jar deployment/app.jar
        
      # Deploy using Railway CLI container
      - name: Link Railway Project
        run: railway link --project ce5752c9-116d-40a3-81bc-bee7acfa7f0c
        
      # Set the Spring profile to railway and deploy
      - name: Deploy JAR directly
        run: |
          cd deployment
          railway variables set SPRING_PROFILES_ACTIVE=railway
          railway up --service identity-service --detach
